services:
  - type: web
    name: attendance-system
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    region: oregon
    envVars:
      - key: PORT
        value: 10000

apt_packages:
  - libgl1-mesa-glx
  - libglib2.0-0

