services:
  - type: web
    name: attendance-management-system
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y cmake build-essential python3-dev git
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:app
